### ISSUE TITLE
Names for blocks

### ISSUE THREAD

**Issue by kolodkinaLena** [kolodkinaLena/lesson_4#1]
1. welcome
   2. title
3. header
  4. / 5. menu
  6. / 19. social
7. main-content
8. site-bar
  9. search
  10. dispatch
  11. about-me
  12. news
	13. news-1 
        14. news-date
        15. news-topic
16. footer
   17. copyright
  18. copyright-1 ?

   20. contact-us

**Comment by bIropka** [comment]
Немного запутался в нумерации. Как-то странно Вы пронумеровали :)
Обсудим завтра, тк извлечь из написанного не смог практически ничего :)
